### ISSUE TITLE
Error while loading  'datainfo/list/cls_labels.npy'

### ISSUE THREAD

**Issue by zcuncun** [Unrealluver/dgcn#3]
While running this project, I got an error

'''
Traceback (most recent call last):
  File "/export/zhoubaicun/envs/py3_cuda101/lib/python3.7/site-packages/numpy/lib/npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '\xef'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "read.py", line 10, in <module>
    np.load("datainfo/list/cls_labels.npy", allow_pickle=True)
  File "/export/zhoubaicun/envs/py3_cuda101/lib/python3.7/site-packages/numpy/lib/npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'datainfo/list/cls_labels.npy' as a pickle
'''

It seems that the file on github is corrupted.

My env:
python 3.7.9
numpy 1.19.2
ubuntu 20.04

**Comment by zcuncun** [comment]
I found this file in another repo  (https://github.com/YudeWang/SEAM/blob/c55601649c5fa676836d3ec70ec044541b7d1d83/voc12/cls_labels.npy).
But I can‘t reproduce the result about hrnet. I just ran the command you provided and the mIOU reached 0.58 (20 epochs).
Is there something I miss?
